=== jabarszcz/breezipe/breezipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
    xml:lang="en"
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:br="http://jabarsz.cz/Breezipe"
    targetNamespace="http://jabarsz.cz/Breezipe">

  <annotation>
    <documentation>
      Jean‑Alexandre Barszcz’s Recipe schema.

      This schema, together with the accompanying XSL transforms, is
      an experiment designed to present the dependencies between the
      steps of a recipe (see `step-table.xsl`). These dependencies are
      the primary focus of the model below; additional features may be
      added later.

      The top-level elements are `recipe` and `recipes`, the latter
      allowing a recipe to be divided into multiple parts.

      Because the primary export target is XHTML, the schema permits
      embedded XHTML elements.
    </documentation>
    <documentation>
      Copyright 2026 Jean-Alexandre Barszcz. MIT license:

      Permission is hereby granted, free of charge, to any person
      obtaining a copy of this software and associated documentation
      files (the "Software"), to deal in the Software without
      restriction, including without limitation the rights to use,
      copy, modify, merge, publish, distribute, sublicense, and/or
      sell copies of the Software, and to permit persons to whom the
      Software is furnished to do so, subject to the following
      conditions:

      The above copyright notice and this permission notice shall be
      included in all copies or substantial portions of the Software.

      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
      OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
      NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
      WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
      OTHER DEALINGS IN THE SOFTWARE.
    </documentation>
  </annotation>

  <import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="http://www.w3.org/2001/xml.xsd" />

  <import
      namespace="http://www.w3.org/1999/xhtml"
      schemaLocation="http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd"/>

  <element name="recipes">
    <annotation><documentation>
      The root element 'recipes' is useful for recipes that can be
      subdivided in sub-recipes. For example, for a pastry dough and
      its filling, or a dish and its sauce, etc.
    </documentation></annotation>
    <complexType>
      <sequence>
        <element ref="br:name" minOccurs="0" />
        <group ref="xhtml:xhtml.Flow.mix"
               minOccurs="0" maxOccurs="unbounded" />
        <sequence maxOccurs="unbounded">
          <element ref="br:recipe" />
          <group ref="xhtml:xhtml.Flow.mix"
                 minOccurs="0" maxOccurs="unbounded" />
        </sequence>
      </sequence>
      <attribute name="name" type="string" />
      <attribute ref="xml:lang" />
    </complexType>
  </element>

  <element name="recipe">
    <annotation><documentation>
      This main root element 'recipe' essentially consist of a name
      and a list of steps, potentially interleaved with some xhtml.
    </documentation></annotation>
    <complexType>
      <sequence>
        <element ref="br:name" minOccurs="0" />
        <group ref="xhtml:xhtml.Flow.mix"
               minOccurs="0" maxOccurs="unbounded" />
        <element ref="br:step" maxOccurs="unbounded" />
        <group ref="xhtml:xhtml.Flow.mix" minOccurs="0"
               maxOccurs="unbounded" />
      </sequence>
      <attribute name="id" type="ID" />
      <attribute name="name" type="string" />
      <attribute ref="xml:lang" />
    </complexType>
  </element>

  <complexType name="name-like" mixed="true">
    <annotation><documentation>
      The names of elements describe these elements in-place (ex. the
      recipe name as an XHTML heading), as well as in reference (using
      the 'ref' element).

      Since named elements are also link targets, and the names appear
      in the link text, they can contain text and any XHTML that is
      allowed in XHTML anchors (inline XHTML except other anchors).

      Some elements are 'name-like' (ingredients, refs, results) and
      their content directly equate to their name. Others contain more
      elements/structure (recipe, step, group), so their name appears
      under the name-like 'name' element.
    </documentation></annotation>
    <group ref="xhtml:xhtml.InlNoAnchor.mix" maxOccurs="unbounded" />
  </complexType>

  <element name="name" type="br:name-like" />

  <element name="step">
    <annotation><documentation>
      Steps represent one action with inputs and outputs. The step
      element represents its own main result (or output) and can be
      given an identifier attribute 'id' for reference. Secondary
      results are noted with the 'result' element. Inputs include
      (optionally grouped) ingredients, and references to other steps
      (main output), their (secondary) results, or other identified
      recipes (when a top-level 'recipes' element is used).

      A short name (attribute 'short') describes the step concisely; a
      verb is recommended, ex.: "Infuse", or "Mix".

      For the purposes of the summary step-table, all steps except the
      last one should be referenced exactly once. The last step
      represents the result of its recipe and is implicitly the root
      of the recipe's dependency tree.
    </documentation></annotation>
    <complexType mixed="true">
      <sequence>
        <choice maxOccurs="unbounded">
          <element ref="br:ingredient" />
          <element ref="br:group" />
          <element ref="br:ref" />
          <element ref="br:result" />
          <group ref="xhtml:xhtml.BlkNoForm.mix" />
        </choice>
        <element ref="br:name" minOccurs="0" />
      </sequence>
      <attribute name="id" type="ID" />
      <attribute name="short" type="string" />
      <attribute name="name" type="string" />
    </complexType>
  </element>

  <element name="ingredient">
    <complexType mixed="true">
      <complexContent>
        <extension base="br:name-like">
          <sequence>
            <element ref="br:note" minOccurs="0" />
          </sequence>
          <attribute name="quantity" type="string" />
          <attribute name="unit" type="string" />
          <attribute name="note" type="string" />
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="note" type="br:inline" />

  <complexType name="inline" mixed="true">
    <group ref="xhtml:xhtml.Inline.mix" maxOccurs="unbounded" />
  </complexType>

  <element name="group">
    <annotation><documentation>
      This element serves to group ingredients together with
      (optionally) a name.
    </documentation></annotation>
    <complexType mixed="true">
      <sequence>
        <element ref="br:name" minOccurs="0" />
        <element ref="br:ingredient" maxOccurs="unbounded" />
      </sequence>
      <attribute name="name" type="string" />
    </complexType>
  </element>

  <element name="ref">
    <annotation><documentation>
      References appear in recipe steps to signify that the step uses
      the referred element and also depends on its completion to
      begin.

      Reference targets must have the corresponding ID. They include:
      other sub-recipes under the same 'recipes' element, steps (a
      referenced step represents its main product) and results
      (secondary products of steps).

      All elements should only be referenced once for the summarizing
      step-table to build correctly.
    </documentation></annotation>
    <complexType mixed="true">
      <complexContent>
        <extension base="br:name-like">
          <attribute name="r" type="IDREF" />
          <attribute name="quantity" type="string" />
          <attribute name="unit" type="string" />
          <attribute name="note" type="string" />
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="result">
    <annotation><documentation>
      This element represents a secondary result of a step (which
      represents its own main result). It must have an ID which should
      be referenced exactly once.
    </documentation></annotation>
    <complexType mixed="true">
      <complexContent>
        <extension base="br:name-like">
          <attribute name="id" type="ID" use="required" />
        </extension>
      </complexContent>
    </complexType>
  </element>

</schema>

=== jabarszcz/breezipe/examples/wrap_de_laitue_au_tofu.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../breezipe-xhtml.xsl"?>
<recipe
    xml:lang="fr-CA"
    xmlns="http://jabarsz.cz/Breezipe"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jabarsz.cz/Breezipe
                        ../breezipe.xsd">

  <name>Wraps de laitue au tofu épicé (façon Joey's)</name>

  <step short="Ré-hydrater" id="champis">
    Ré-hydrater des <ingredient quantity="1"
    unit="poignée">champignons séchés</ingredient> en les recouvrant
    d'eau bouillante pour une dizaine de minutes.
  </step>

  <step short="Mélanger" id="sauce">
    Préparer la sauce en mélangeant dans un bol la <ingredient
    quantity="3" unit="c. à soupe">sauce soya</ingredient>, le
    <ingredient quantity="2" unit="c. à soupe">vinaigre de
    riz</ingredient>, l’<ingredient quantity="1" unit="c. à thé">huile
    de sésame</ingredient> et la <ingredient quantity="1" unit="c. à
    thé">sauce piquante Gochujang</ingredient>.
  </step>

  <step short="Presser" id="tofu">
    Presser le <ingredient quantity="1" unit="bloc">tofu</ingredient>
    et le déchirer en petits morceaux.
  </step>

  <step short="Dorer" id="tofu-dore">
    Faire chauffer l'<ingredient quantity="2" unit="c. à soupe">huile
    de canola</ingredient> dans le wok. Ajouter le <ref r="tofu">tofu
    morcelé</ref> et le faire frire jusqu'à ce qu'il soit adéquatement
    doré et croustillant en surface. Réserver le tofu doré dans un
    bol.
  </step>

  <step short="Dorer" id="aromates">
    Dans le wok chaud, dorer les <group><name>aromates</name>: d'abord
    les <ingredient
    quantity="2">échalotes<note>coupées</note></ingredient> pour
    quelques minutes, puis ajouter l'<ingredient quantity="1"
    unit="gousse">ail <note>pressé</note></ingredient> et le
    <ingredient quantity="1" unit="c. à thé">gingembre frais
    <note>râpé à la microplane</note></ingredient></group>.
  </step>

  <step short="Ajouter" id="wok">
    Pendant que les aromates finissent de dorer, égouter et hacher les
    <ref r="champis">champignons ré-hydratés</ref> en petits morceaux,
    puis les ajouter au <ref r="aromates">wok</ref> et les dorer.
  </step>

  <step short="Mélanger" id="melange">
    Ajouter le <ref r="tofu-dore">tofu</ref> et la <ref r="sauce" />
    dans le <ref r="wok" />. Bien mélanger et réchauffer le tout.
  </step>

  <step short="Griller" id="arachides">
    Faire griller les <ingredient quantity="1"
    unit="poignée">arachides</ingredient> dans une petite poêle.
  </step>
  
  <step short="Assembler">
    Disposer la <ingredient quantity="3" unit="feuilles par
    personne">laitue <note>lavée</note></ingredient> dans les
    assiettes, y déposer le <ref r="melange">mélange</ref> et garnir:
    <group name="garnitures"><ingredient>nouilles chow-mein
    croustillantes</ingredient>, <ingredient quantity="1">carotte
    <note>rapée</note></ingredient>,
    <ingredient>mayonnaise à la sriracha</ingredient>,
    <ingredient>assaisonnement chili crisp</ingredient></group> et
    <ref r="arachides">arachides grillées</ref>.
  </step>

  <!-- <xhtml:p>This recipe is adapted from <xhtml:a -->
  <!-- href="https://www.ricardocuisine.com/en/recipes/5346-blueberry-muffins">Ricardo's</xhtml:a>.</xhtml:p> -->

</recipe>

=== jabarszcz/breezipe/examples/blueberry_muffins.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../breezipe-xhtml.xsl"?>
<recipe
    xml:lang="en-CA"
    xmlns="http://jabarsz.cz/Breezipe"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jabarsz.cz/Breezipe
                        ../breezipe.xsd">

  <name>Blueberry yogurt muffins</name>

  <step id="preheated" short="Pre-heat">
    Pre-heat oven to 350°F (180°C).
  </step>

  <step id="dry" name="dry mix" short="Mix">
    Combine and mix the <group><name>dry ingredients</name>:
    <ingredient quantity="1 ½" unit="cups">flour</ingredient>,
    <ingredient quantity="1" unit="cup" note="100g">rolled
    oats</ingredient>, <ingredient quantity="1" unit="cup"
    note="200g">sugar</ingredient>, <ingredient quantity="2"
    unit="tsp">baking powder</ingredient> and <ingredient quantity="½"
    unit="tsp">salt</ingredient></group>.
  </step>

  <step id="wet" name="wet mix" short="Whisk">
    Combine and whisk the <group><name>wet ingredients</name>:
    <ingredient quantity="1" unit="cup">yogurt</ingredient>,
    <ingredient note="e.g. canola or grape seed" quantity="½"
    unit="cup">vegetable oil</ingredient>, <ingredient
    quantity="2">eggs</ingredient> and <ingredient quantity="1"
    unit="tsp">vanilla</ingredient></group>.
  </step>

  <step id="batter" short="Stir">
    Stir the <ref r="dry" /> into the <ref r="wet" />.
  </step>

  <step id="blueberried_batter" name="batter" short="Add">
    Gently fold the <ingredient quantity="1 ¾" unit="cup">frozen
    blueberries</ingredient> into the <ref r="batter" />.
  </step>

  <step id="muffins" short="Portion">
    Portion the <ref r="blueberried_batter" /> into 12 silicone muffin
    cups.
  </step>

  <step short="Bake">
    In the <ref r="preheated">pre-heated oven</ref>, bake the <ref
    r="muffins" /> for about 25 minutes.
  </step>

  <xhtml:p>This recipe is adapted from <xhtml:a
  href="https://www.ricardocuisine.com/en/recipes/5346-blueberry-muffins">Ricardo's</xhtml:a>.</xhtml:p>

</recipe>

=== jabarszcz/breezipe/examples/red_lentil_dahl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xslt-param name="css" select="'../recipe.css'"?>
<?xml-stylesheet type="text/xsl" href="../breezipe-xhtml.xsl"?>
<recipe
    xml:lang="en-CA"
    xmlns="http://jabarsz.cz/Breezipe"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jabarsz.cz/Breezipe
                        ../breezipe.xsd">

  <name>Red Lentil Dahl</name>

  <step id="hot-pan" short="Heat">
    Heat <ingredient quantity="1" unit="teaspoon">olive
    oil</ingredient> (or coconut oil) in a large pan over medium heat.
  </step>

  <step id="cook-onion" short="Brown">
    Add <ingredient quantity="2">onions<note>diced</note></ingredient>
    to the <ref r="hot-pan">hot pan</ref> and cook gently for 5
    minutes.
  </step>

  <step id="add-aromatics" short="Aromatize">
    Add the <group><name>aromatics</name>: <ingredient
    quantity="3">garlic cloves<note>pressed</note></ingredient>,
    <ingredient quantity="1" unit="tablespoon">fresh
    ginger<note>peeled and grated</note></ingredient> and <ingredient
    quantity="½" unit="">red chilli<note>finely
    chopped</note></ingredient></group> to the <ref
    r="cook-onion">pan</ref> and sauté for a few minutes. The red
    chilli can be replaced by ½ tsp of dried chilli flakes.
  </step>

  <step id="toast-spices" short="Toast spices">
    Add the <group><name>spices</name>: <ingredient quantity="½"
    unit="teaspoon">cumin seeds<note>freshly
    ground</note></ingredient>, <ingredient quantity="½"
    unit="teaspoon">coriander seeds<note>freshly
    ground</note></ingredient>, <ingredient quantity="½"
    unit="teaspoon">mustard seeds<note>freshly
    ground</note></ingredient>, <ingredient quantity="2"
    unit="teaspoons">ground turmeric</ingredient> and <ingredient
    quantity="1" unit="teaspoon">garam masala</ingredient></group> to
    the <ref r="add-aromatics">pan</ref> and cook 1 minute.
  </step>

  <step id="add-main" short="Add">
    Stir <ref r="toast-spices">in</ref> the <group><name>main
    ingredients</name>: <ingredient quantity="1" unit="cup">dried red
    lentils</ingredient>, <ingredient quantity="1" unit="can">chopped
    tomatoes</ingredient>, <ingredient quantity="1" unit="can">coconut
    milk</ingredient>, and <ingredient quantity="2"
    unit="cups">vegetable stock</ingredient></group>. Season with
    salt and pepper.
  </step>

  <step id="simmer" short="Simmer">
    Bring to a gentle simmer and cook 15–20 minutes, stirring
    occasionally, until the <ref r="add-main">dahl</ref> is thick and
    the lentils are tender.
  </step>

  <step id="finish" short="Finish">
    Stir <ref r="simmer">in</ref> the <ingredient quantity="½"
    unit="lemon">juice of half a lemon</ingredient> and <ingredient
    quantity="2" unit="handfuls">fresh spinach</ingredient> until the
    spinach wilts.
  </step>

  <step id="serve" short="Serve">
    Serve the <ref r="finish">dahl</ref> warm with rice, naan, or
    poppadoms. It freezes well for later meals.
  </step>

  <xhtml:p>Adapted from the original <xhtml:a
  href="https://veggiedesserts.com/red-lentil-dahl/">Veggie Desserts
  recipe</xhtml:a>.</xhtml:p>

</recipe>

=== jabarszcz/breezipe/examples/kombucha_first_fermentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../breezipe-xhtml.xsl"?>
<recipe
    xml:lang="en-CA"
    xmlns="http://jabarsz.cz/Breezipe"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jabarsz.cz/Breezipe
                        ../breezipe.xsd">

  <name>Kombucha (first fermentation)</name>

  <step id="quasifulljar" short="Measure">
    Fill a ~4L glass jar with <ingredient quantity="3.75"
    unit="L">water</ingredient>, leaving space for an additional cup
    of liquid.
  </step>

  <step id="pot" short="Pour">
    Pour about 1.5L of <ref r="quasifulljar">water from the glass
    jar</ref> to a 3L pot. Set aside the <result id="water-jar">now
    half-full jar</result>.
  </step>

  <step id="heating" short="Heat">
     Put the <ref r="pot" /> on high heat.
  </step>

  <step id="infusion" short="Infuse">
    Add <ingredient quantity="6" unit="tbs">black tea
    leaves<note>e.g. Earl Grey</note></ingredient> to the <ref
    r="heating">heating water</ref>, mix and bring to a simmer, then
    leave off the heat for 10 minutes for the tea to infuse.
  </step>

  <step id="cool" short="Cool">
    Cool down the <ref r="infusion" /> by diluting it with <ref
    r="water-jar" quantity="1" unit="L" note="approx.">cold water from
    the jar</ref>. Set aside the <result id="non-empty-jar">jar with
    remaining water</result> (leave at least a few cups to minimize
    the thermal shock to the glass jar later).
  </step>

  <step id="tea_jar" short="Filter">
    Pour the <ref r="cool">infused and cooled tea</ref> back into the
    <ref r="non-empty-jar" />, through a sieve to catch the few
    floating leaves. Most of the tea leaves usually stay at the bottom
    my pot.
  </step>

  <step id="sweet_tea" short="Sweeten">
    Add <ingredient quantity="1" unit="cup"
    note="200g">sugar</ingredient> to the <ref r="tea_jar">tea
    jar</ref> and mix until it dissolves completely.
  </step>

  <step id="inoculated" short="Pitch SCOBY">
    After making sure that the <ref r="sweet_tea">sweet tea</ref> is
    not hotter than 40°C, pour and stir in a starter culture of
    <ingredient quantity="1" unit="cup">raw kombucha<note>i.e. not
    pasteurized</note></ingredient>, either from a previous batch or a
    bottle of raw kombucha from the store. Note that the SCOBY is the
    culture of bacteria and yeast that live in the unpasteurized
    kombucha, not the pellicle that can form on top of the liquid.
  </step>

  <step short="Ferment">
    Cover the jar with a cloth and leave the <ref
    r="inoculated">inoculated sweet tea</ref> in a dark place, ideally
    between 20°C and 25°C. A pellicle should form at the top in the
    following days and some bubbles may get trapped underneath, but do
    regularly make sure that the culture is not colonised by other
    organisms: it should have a pleasant smell, and no fuzzy patches
    on the surface.  Ferment to preference, until the brew has
    acidified and consumed enough sugar.

    <xhtml:p>I've measured the sugar content with a refractometer and
    my brew starts at 6-7% and I wait until 3.5% for the second
    fermentation.</xhtml:p>
  </step>

</recipe>

=== jabarszcz/breezipe/examples/braisé_d_aubergines.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xslt-param name="css" select="'../recipe.css'"?>
<?xml-stylesheet type="text/xsl" href="../breezipe-xhtml.xsl"?>
<recipe
    xml:lang="fr-CA"
    xmlns="http://jabarsz.cz/Breezipe"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jabarsz.cz/Breezipe
                        ../breezipe.xsd">

  <name>Braisé d’aubergines, pois chiches, érable et harissa</name>

  <step id="legumes-revenus" short="Dorer">
    Verser l'<ingredient quantity="¼" unit="tasse">huile
    d'olive</ingredient> dans une cocotte chaude, et y faire revenir
    les <group><name>légumes</name>: <ingredient quantity="1
    grosse">aubergine<note>coupées en gros cubes</note></ingredient>,
    <ingredient quantity="2">oignons
    rouges<note>émincés</note></ingredient>, <ingredient quantity="1"
    unit="tasse">carottes <note>en petits dés</note></ingredient>,
    <ingredient quantity="2">poivrons rouges<note>en
    lanières</note></ingredient> </group>.
  </step>

  <step id="aromatises" short="Aromatiser">
    Ajouter aux <ref r="legumes-revenus">légumes</ref> les
    <group><name>aromates</name>: <ingredient quantity="3">gousses
    d’ail<note>pressées</note></ingredient>, <ingredient quantity="1"
    unit="c. à thé">paprika</ingredient>, <ingredient quantity="1"
    unit="c. à thé">curcuma</ingredient>, <ingredient quantity="1"
    unit="c. à thé">coriandre moulue</ingredient>, <ingredient
    quantity="2" unit="c. à thé">origan séché</ingredient>,
    <ingredient quantity="½" unit="c. à thé">cumin</ingredient>,
    <ingredient quantity="1">bâton de cannelle</ingredient>,
    <ingredient quantity="2">feuilles de laurier</ingredient>,
    <ingredient quantity="1 ½" unit="c. à soupe">sauce
    harissa</ingredient> et le <ingredient quantity="1 ½" unit="c. à
    thé">sel</ingredient></group>, puis cuire encore 2 minutes.
  </step>

  <step id="deglace" short="Déglacer">
    Déglacer les <ref r="aromatises">légumes aromatisés</ref> avec le
    <ingredient quantity="2" unit="c. à soupe">vinaigre de vin
    rouge</ingredient>.
  </step>

  <step id="melange" short="Ajouter">
    Ajouter à la <ref r="deglace">cocotte</ref> <group>le <ingredient
    quantity="2" unit="c. à soupe">sirop d’érable</ingredient>, les
    <ingredient quantity="1" unit="boîte de 796 ml">tomates entières
    San Marzano</ingredient> et le <ingredient quantity="2 ½"
    unit="tasse">bouillon de légumes</ingredient></group>.
  </step>

  <step id="mijote" short="Mijoter">
    Porter le <ref r="melange">mélange</ref> à ébulition puis laisser
    mijoter à feu doux pendant 1 heure en brassant de temps en temps.
  </step>

  <step id="servir" short="Servir">
    Servir le <ref r="mijote">braisé d'aubergines</ref> avec des
    <group><name>garnitures au choix</name>: <ingredient quantity="½"
    unit="tasse">persil frais haché</ingredient>, <ingredient
    quantity="½" unit="tasse">coriandre fraîche hachée</ingredient>,
    <ingredient quantity="2">avocats<note>tranchés</note></ingredient>
    et/ou <ingredient quantity="⅓" unit="tasse">noix de pin
    grillées</ingredient></group>.
  </step>

  <xhtml:p>Recette tirée <xhtml:a href="https://www.kpourkatrine.com/fr/recettes/mes-recettes-derable/braise-daubergines-pois-chiches-erable-et-harissa/">du site de K pour Katrine</xhtml:a>.</xhtml:p>

</recipe>
