=== jabarszcz/breezipe/breezipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
    xml:lang="en"
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:br="http://jabarsz.cz/Breezipe"
    targetNamespace="http://jabarsz.cz/Breezipe">

  <annotation>
    <documentation>
      Jean‑Alexandre Barszcz’s Recipe schema.

      This schema, together with the accompanying XSL transforms, is
      an experiment designed to present the dependencies between the
      steps of a recipe (see `step-table.xsl`). These dependencies are
      the primary focus of the model below; additional features may be
      added later.

      The top-level elements are `recipe` and `recipes`, the latter
      allowing a recipe to be divided into multiple parts.

      Because the primary export target is XHTML, the schema permits
      embedded XHTML elements.
    </documentation>
    <documentation>
      Copyright 2026 Jean-Alexandre Barszcz. MIT license:

      Permission is hereby granted, free of charge, to any person
      obtaining a copy of this software and associated documentation
      files (the "Software"), to deal in the Software without
      restriction, including without limitation the rights to use,
      copy, modify, merge, publish, distribute, sublicense, and/or
      sell copies of the Software, and to permit persons to whom the
      Software is furnished to do so, subject to the following
      conditions:

      The above copyright notice and this permission notice shall be
      included in all copies or substantial portions of the Software.

      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
      OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
      NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
      WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
      OTHER DEALINGS IN THE SOFTWARE.
    </documentation>
  </annotation>

  <import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="http://www.w3.org/2001/xml.xsd" />

  <import
      namespace="http://www.w3.org/1999/xhtml"
      schemaLocation="http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd"/>

  <element name="recipes">
    <annotation><documentation>
      The root element 'recipes' is useful for recipes that can be
      subdivided in sub-recipes. For example, for a pastry dough and
      its filling, or a dish and its sauce, etc.
    </documentation></annotation>
    <complexType>
      <sequence>
        <element ref="br:name" minOccurs="0" />
        <group ref="xhtml:xhtml.Flow.mix"
               minOccurs="0" maxOccurs="unbounded" />
        <sequence maxOccurs="unbounded">
          <element ref="br:recipe" />
          <group ref="xhtml:xhtml.Flow.mix"
                 minOccurs="0" maxOccurs="unbounded" />
        </sequence>
      </sequence>
      <attribute name="name" type="string" />
      <attribute ref="xml:lang" />
    </complexType>
  </element>

  <element name="recipe">
    <annotation><documentation>
      This main root element 'recipe' essentially consist of a name
      and a list of steps, potentially interleaved with some xhtml.
    </documentation></annotation>
    <complexType>
      <sequence>
        <element ref="br:name" minOccurs="0" />
        <group ref="xhtml:xhtml.Flow.mix"
               minOccurs="0" maxOccurs="unbounded" />
        <element ref="br:step" maxOccurs="unbounded" />
        <group ref="xhtml:xhtml.Flow.mix" minOccurs="0"
               maxOccurs="unbounded" />
      </sequence>
      <attribute name="id" type="ID" />
      <attribute name="name" type="string" />
      <attribute ref="xml:lang" />
    </complexType>
  </element>

  <complexType name="name-like" mixed="true">
    <annotation><documentation>
      The names of elements describe these elements in-place (ex. the
      recipe name as an XHTML heading), as well as in reference (using
      the 'ref' element).

      Since named elements are also link targets, and the names appear
      in the link text, they can contain text and any XHTML that is
      allowed in XHTML anchors (inline XHTML except other anchors).

      Some elements are 'name-like' (ingredients, refs, results) and
      their content directly equate to their name. Others contain more
      elements/structure (recipe, step, group), so their name appears
      under the name-like 'name' element.
    </documentation></annotation>
    <group ref="xhtml:xhtml.InlNoAnchor.mix" maxOccurs="unbounded" />
  </complexType>

  <element name="name" type="br:name-like" />

  <element name="step">
    <annotation><documentation>
      Steps represent one action with inputs and outputs. The step
      element represents its own main result (or output) and can be
      given an identifier attribute 'id' for reference. Secondary
      results are noted with the 'result' element. Inputs include
      (optionally grouped) ingredients, and references to other steps
      (main output), their (secondary) results, or other identified
      recipes (when a top-level 'recipes' element is used).

      A short name (attribute 'short') describes the step concisely; a
      verb is recommended, ex.: "Infuse", or "Mix".

      For the purposes of the summary step-table, all steps except the
      last one should be referenced exactly once. The last step
      represents the result of its recipe and is implicitly the root
      of the recipe's dependency tree.
    </documentation></annotation>
    <complexType mixed="true">
      <sequence>
        <choice maxOccurs="unbounded">
          <element ref="br:ingredient" />
          <element ref="br:group" />
          <element ref="br:ref" />
          <element ref="br:result" />
          <group ref="xhtml:xhtml.BlkNoForm.mix" />
        </choice>
        <element ref="br:name" minOccurs="0" />
      </sequence>
      <attribute name="id" type="ID" />
      <attribute name="short" type="string" />
      <attribute name="name" type="string" />
    </complexType>
  </element>

  <element name="ingredient">
    <complexType mixed="true">
      <complexContent>
        <extension base="br:name-like">
          <sequence>
            <element ref="br:note" minOccurs="0" />
          </sequence>
          <attribute name="quantity" type="string" />
          <attribute name="unit" type="string" />
          <attribute name="note" type="string" />
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="note" type="br:inline" />

  <complexType name="inline" mixed="true">
    <group ref="xhtml:xhtml.Inline.mix" maxOccurs="unbounded" />
  </complexType>

  <element name="group">
    <annotation><documentation>
      This element serves to group ingredients together with
      (optionally) a name.
    </documentation></annotation>
    <complexType mixed="true">
      <sequence>
        <element ref="br:name" minOccurs="0" />
        <element ref="br:ingredient" maxOccurs="unbounded" />
      </sequence>
      <attribute name="name" type="string" />
    </complexType>
  </element>

  <element name="ref">
    <annotation><documentation>
      References appear in recipe steps to signify that the step uses
      the referred element and also depends on its completion to
      begin.

      Reference targets must have the corresponding ID. They include:
      other sub-recipes under the same 'recipes' element, steps (a
      referenced step represents its main product) and results
      (secondary products of steps).

      All elements should only be referenced once for the summarizing
      step-table to build correctly.
    </documentation></annotation>
    <complexType mixed="true">
      <complexContent>
        <extension base="br:name-like">
          <attribute name="r" type="IDREF" />
          <attribute name="quantity" type="string" />
          <attribute name="unit" type="string" />
          <attribute name="note" type="string" />
        </extension>
      </complexContent>
    </complexType>
  </element>

  <element name="result">
    <annotation><documentation>
      This element represents a secondary result of a step (which
      represents its own main result). It must have an ID which should
      be referenced exactly once.
    </documentation></annotation>
    <complexType mixed="true">
      <complexContent>
        <extension base="br:name-like">
          <attribute name="id" type="ID" use="required" />
        </extension>
      </complexContent>
    </complexType>
  </element>

</schema>

=== jabarszcz/breezipe/examples/quartiers_courge_rotie_sur_puree.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xslt-param name="css" select="'../recipe.css'"?>
<?xml-stylesheet type="text/xsl" href="../breezipe-xhtml.xsl"?>
<recipes xml:lang="fr-CA"
         xmlns="http://jabarsz.cz/Breezipe"
         xmlns:xhtml="http://www.w3.org/1999/xhtml"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jabarsz.cz/Breezipe
         ../breezipe.xsd">

  <recipe id="courge-rotie">
    <name>Courge rôtie</name>

    <step id="prechauffer" short="Préchauffer">
      Préchauffer le four à 375 °F et placer la grille au centre.
    </step>

    <step id="courge" short="Disposer">
      Disposer la <ingredient quantity="1">courge
      Buttercup<note>coupée en quartiers</note></ingredient> sur une
      plaque de cuisson recouverte de papier parchemin.
    </step>

    <step id="garnie" short="Garnir">
      Dans un bol, mélanger la <ingredient quantity="1"
      unit="tasse">chapelure panko</ingredient>, le <ingredient
      quantity="⅓" unit="tasse">beurre
      <note>ramolli</note></ingredient>, des <ingredient quantity="1"
      unit="c. à soupe">herbes au choix <note>ex. origan,
      persil</note></ingredient>, et saler/poiver au goût. Étaler ce
      mélange sur la surface des <ref r="courge">quartiers de
      courge</ref>.
    </step>

    <step short="Cuire">
      <ref r="prechauffer">Enfourner</ref> la <ref r="garnie">courge
      garnie</ref> pendant 30-35 minutes jusqu'à ce qu'elle soit
      tendre et légèrement dorée.
    </step>
  </recipe>

  <recipe id="sauce">
    <name>Sauce au vinaigre balsamique, oignons et champignons</name>

    <xhtml:p>Cette partie peut être faite d'avance et réchauffée.</xhtml:p>

    <step id="huile" short="Chauffer">
      Faire chauffer <ingredient quantity="2" unit="c. à soupe">huile
      végétale</ingredient> dans une poêle à feu moyen.
    </step>

    <step id="oignon" short="Dorer">
      <ref r="huile">Y</ref> ajouter l'<ingredient
      quantity="1">oignon<note>haché</note></ingredient> et
      l'<ingredient quantity="1"
      unit="gousse">ail<note>pressé</note></ingredient>, et faire
      revenir environ 10 minutes ou jusqu'à ce que l'oignon soit doré.
    </step>

    <step id="bouillon" short="Bouillir">
      Pendant que l'oignon cuit, bouillir de l'<ingredient
      quantity="1" unit="tasse">eau</ingredient> et y incorporer une
      <ingredient quantity="1" unit="c. à thé">base à
      bouillon<note>ex. Better than Bouillon</note></ingredient>.
    </step>

    <step id="champignons" short="Ajouter">
      Ajouter les <ingredient quantity="2"
      unit="tasses">champignons<note>émincés</note></ingredient> dans
      la <ref r="oignon">poêle</ref>, et poursuivre la cuisson environ
      10 minutes en remuant régulièrement.
    </step>

    <step id="deglace" short="Déglacer">
      Verser le <ingredient quantity="¼" unit="tasse">vinaigre
      balsamique</ingredient> dans la <ref
      r="champignons">poêle</ref> et laisser réduire de moitié
      pendant environ 5 minutes.
    </step>

    <step short="Épaissir">
      Délayer la <ingredient quantity="1" unit="c. à thé">fécule de
      maïs</ingredient> avec un peu du <ref r="bouillon"/>. Ensuite,
      verser la fécule délayée et le reste du bouillon dans la <ref
      r="deglace">poêle</ref>. Porter à ébullition puis cuire
      10-15 minutes pour que ça épaississe. Assaisonner.
    </step>
  </recipe>

  <recipe id="puree">
    <name>Purée de haricots blancs et crème</name>

    <xhtml:p>Cette partie peut être faite d'avance et réchauffée.</xhtml:p>

    <step id="creme-chaude" short="Chauffer">
      Faire chauffer <ingredient quantity="½"
      unit="tasse">crème</ingredient> dans une casserole à feu moyen.
    </step>

    <step id="melange-a-puree" short="Ajouter">
      <ref r="creme-chaude">Y</ref> ajouter <ingredient quantity="1"
      unit="boîte de 540 ml">haricots blancs</ingredient>, <ingredient
      quantity="½" unit="tasse">fromage gouda
      fumé<note>râpé</note></ingredient>, puis saler/poivrer au goût.
    </step>

    <step short="Pied-mélanger">
      Réduire <ref r="melange-a-puree">le tout</ref> en purée à l'aide
      d'un pied-mélangeur.
    </step>
  </recipe>

  <recipe id="salade">
    <name>Salade croquante</name>

    <step short="Mélanger">
      Dans un grand bol, combiner <ingredient quantity="2"
      unit="tasses">choux de
      Bruxelles<note>effeuillés</note></ingredient>, <ingredient
      quantity="1">oignon vert<note>émincé</note></ingredient>,
      <ingredient quantity="2" unit="c. à soupe">crème
      sûre</ingredient>, <ingredient quantity="1" unit="c. à
      soupe">jus de citron</ingredient>, <ingredient quantity="1"
      unit="c. à soupe">miel<note>ou sirop
      d'érable</note></ingredient> et <ingredient quantity="2"
      unit="c. à soupe">pacanes<note>rôties et
      concassées</note></ingredient>. Assaisonner et bien mélanger.
    </step>
  </recipe>

  <recipe>
    <name>Quartiers de courge rôtis sur purée de haricots blancs</name>

    <step short="Assembler">
      Sur chaque assiette, déposer une couche de <ref
      r="puree">purée</ref>, former un nid et y verser généreusement
      la <ref r="sauce">sauce</ref>. Déposer quelques <ref
      r="courge-rotie">quartiers de courge rôtie</ref> dessus, puis
      parsemer de <ref r="salade">salade</ref>.
    </step>
  </recipe>

  <xhtml:p>Recette tirée de <xhtml:a
  href="https://www.troisfoisparjour.com/fr/recettes/plats-principaux/legumineuses/quartiers-de-courge-rotis-sur-puree-de-haricots-blancs/">
  Trois fois par jour</xhtml:a>.</xhtml:p>
</recipes>
